<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukDetailSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('produk_detail')->insert([
            [
                'id_produk' => 1,
                'nama_varian' => '1 Liter',
                'foto' => 'produk/bimoli-1l.png',
                'harga_modal' => 16000,
                'harga_jual' => 19000,
                'stok' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 1,
                'nama_varian' => '2 Liter',
                'foto' => 'produk/bimoli-2l.png',
                'harga_modal' => 32000,
                'harga_jual' => 37000,
                'stok' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 2,
                'nama_varian' => '5 Kg',
                'foto' => 'produk/beras-5kg.png',
                'harga_modal' => 56000,
                'harga_jual' => 63000,
                'stok' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 2,
                'nama_varian' => '10 Kg',
                'foto' => 'produk/beras-10kg.png',
                'harga_modal' => 110000,
                'harga_jual' => 125000,
                'stok' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 3,
                'nama_varian' => 'Botol 600ml',
                'foto' => 'produk/aqua-600.png',
                'harga_modal' => 2500,
                'harga_jual' => 3500,
                'stok' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 3,
                'nama_varian' => 'Pack 12 Botol',
                'foto' => 'produk/aqua-pack.png',
                'harga_modal' => 27000,
                'harga_jual' => 33000,
                'stok' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 3,
                'nama_varian' => 'Teh mela',
                'foto' => 'produk/aqua-pack.png',
                'harga_modal' => 27000,
                'harga_jual' => 33000,
                'stok' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 4,
                'nama_varian' => '200ml',
                'foto' => 'produk/tehkotak-200.png',
                'harga_modal' => 3000,
                'harga_jual' => 4000,
                'stok' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 4,
                'nama_varian' => '1 Liter',
                'foto' => 'produk/tehkotak-1l.png',
                'harga_modal' => 9000,
                'harga_jual' => 12000,
                'stok' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 5,
                'nama_varian' => '800gr',
                'foto' => 'produk/rinso-800gr.png',
                'harga_modal' => 18000,
                'harga_jual' => 22000,
                'stok' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 5,
                'nama_varian' => '1.6Kg',
                'foto' => 'produk/rinso-16kg.png',
                'harga_modal' => 34000,
                'harga_jual' => 39000,
                'stok' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 6,
                'nama_varian' => 'Pack 3pcs',
                'foto' => 'produk/spons-3pcs.png',
                'harga_modal' => 5000,
                'harga_jual' => 8000,
                'stok' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 6,
                'nama_varian' => 'Pack 6pcs',
                'foto' => 'produk/spons-6pcs.png',
                'harga_modal' => 9000,
                'harga_jual' => 13000,
                'stok' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 7,
                'nama_varian' => 'Merah 70gr',
                'foto' => 'produk/lifebuoy-merah.png',
                'harga_modal' => 3000,
                'harga_jual' => 4000,
                'stok' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 7,
                'nama_varian' => 'Hijau 70gr',
                'foto' => 'produk/lifebuoy-hijau.png',
                'harga_modal' => 3000,
                'harga_jual' => 4000,
                'stok' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 8,
                'nama_varian' => '100ml',
                'foto' => 'produk/sanitizer-100.png',
                'harga_modal' => 6000,
                'harga_jual' => 9000,
                'stok' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 8,
                'nama_varian' => '250ml',
                'foto' => 'produk/sanitizer-250.png',
                'harga_modal' => 12000,
                'harga_jual' => 17000,
                'stok' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 9,
                'nama_varian' => '16 Batang',
                'foto' => 'produk/djarum-16.png',
                'harga_modal' => 23000,
                'harga_jual' => 27000,
                'stok' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 9,
                'nama_varian' => '12 Batang',
                'foto' => 'produk/djarum-12.png',
                'harga_modal' => 18000,
                'harga_jual' => 21000,
                'stok' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 10,
                'nama_varian' => 'Pack 2pcs',
                'foto' => 'produk/baterai-2pcs.png',
                'harga_modal' => 6000,
                'harga_jual' => 9000,
                'stok' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_produk' => 10,
                'nama_varian' => 'Pack 4pcs',
                'foto' => 'produk/baterai-4pcs.png',
                'harga_modal' => 11000,
                'harga_jual' => 15000,
                'stok' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
